# Generated by Django 4.0.10 on 2023-04-27 09:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_ethnicgroup_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethnicgroup',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.ethnic_group_image_path),
        ),
    ]
