# Generated by Django 4.0.10 on 2023-06-15 13:45

import core.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chief_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(blank=True, choices=[('article', 'Article'), ('conference_paper', 'Conference paper'), ('research_paper', 'Research paper'), ('book', 'Book'), ('chapters', 'Chapter')], max_length=100)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.helpers.document_path)),
                ('is_published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
