# Generated by Django 4.0.10 on 2023-06-21 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='document_type',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('conference_paper', 'Conference paper'), ('research_paper', 'Research paper'), ('book', 'Book'), ('chapter', 'Chapter')], max_length=100),
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_type', models.CharField(choices=[('cultural', 'Cultural'), ('natural', 'Natural')], max_length=20)),
                ('importance', models.PositiveIntegerField()),
                ('sensitivity', models.PositiveIntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(blank=True)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.culture')),
                ('ethnic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ethnicgroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
