# Generated by Django 4.0.10 on 2023-05-15 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='ethnic_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ethnic_group', to='core.ethnicgroup'),
        ),
    ]
