# Generated by Django 4.0.10 on 2023-05-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_culture_ethnic_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
