# Generated by Django 4.0.10 on 2023-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_culture_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='geography',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='ethnicgroup',
            name='language',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
