# Generated by Django 4.0.10 on 2023-05-22 07:54

import core.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_culture_tags_alter_ethnicgroup_geography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='image',
            field=models.ImageField(null=True, upload_to=core.helpers.culture_image_path),
        ),
    ]
