# Generated by Django 4.0.10 on 2023-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='importance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='sensitivity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
