# Generated by Django 4.0.10 on 2023-06-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_site_importance_alter_site_sensitivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='importance',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='sensitivity',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
