# Generated by Django 4.0.10 on 2023-07-05 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_name', models.CharField(max_length=100)),
                ('artifact_type', models.CharField(choices=[('clothing', 'Clothing'), ('jewelry', 'Jewelry'), ('tool', 'Tool'), ('other', 'Other')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('historical_significance', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('cultural_significance', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('culture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.culture')),
                ('ethnic_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ethnicgroup')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.site')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
